defmodule Mut.Bootstrap.Overlay do
  @moduledoc "Generates the working-copy mix.exs overlay."

  @type role :: :oracle | :schema

  @overlay """
  # tmp/mut_work/<run_id>/mix.exs (generated by Mut.Bootstrap.Overlay)
  Code.require_file("mix_user.exs", __DIR__)
  mutalisk_user_mod = Mix.Project.get!()
  Mix.Project.pop()
  Application.put_env(:mutalisk, :user_mix_module, mutalisk_user_mod)

  defmodule Mutalisk.WrappedMixProject do
    use Mix.Project

    @mutalisk_path System.fetch_env!("MUTALISK_PATH")
    @mutalisk_role System.get_env("MUTALISK_ROLE", "schema")

    def project do
      user_mod = Application.fetch_env!(:mutalisk, :user_mix_module)
      user = user_mod.project()

      user
      |> Keyword.update(:deps, default_deps(), &add_mutalisk_dep/1)
      |> Keyword.update(:compilers, maybe_prepend_oracle_compiler(default_compilers()), &maybe_prepend_oracle_compiler/1)
    end

    def application do
      user_mod = Application.fetch_env!(:mutalisk, :user_mix_module)

      if function_exported?(user_mod, :application, 0) do
        user_mod.application()
      else
        []
      end
    end

    defp default_deps, do: []
    defp default_compilers, do: Mix.compilers()

    defp add_mutalisk_dep(deps) do
      if Enum.any?(deps, fn
           {:mutalisk, _} -> true
           {:mutalisk, _, _} -> true
           _ -> false
         end) do
        deps
      else
        [{:mutalisk, path: @mutalisk_path, only: [:test], runtime: true} | deps]
      end
    end

    defp maybe_prepend_oracle_compiler(compilers) do
      case @mutalisk_role do
        "oracle" -> [:mut_oracle | compilers]
        _ -> compilers
      end
    end
  end
  """

  @spec materialize(Path.t(), role) :: :ok | {:error, term}
  def materialize(work_copy, role) when role in [:oracle, :schema] do
    mix_exs = Path.join(work_copy, "mix.exs")
    mix_user_exs = Path.join(work_copy, "mix_user.exs")

    cond do
      not File.exists?(mix_exs) ->
        {:error, {:not_a_mix_project, work_copy}}

      File.exists?(mix_user_exs) ->
        {:error, {:already_installed, work_copy}}

      true ->
        assert_not_umbrella!(work_copy)
        :ok = File.rename(mix_exs, mix_user_exs)
        File.write(mix_exs, render(role))
    end
  end

  @spec render(role) :: String.t()
  def render(role) when role in [:oracle, :schema] do
    @overlay
  end

  # Fragile by design for v1: generated or indirect project configs may evade this heuristic.
  @doc false
  @spec assert_not_umbrella!(Path.t()) :: :ok
  def assert_not_umbrella!(work_copy) do
    quoted =
      work_copy
      |> user_mix_path()
      |> File.read!()
      |> Code.string_to_quoted!()

    if umbrella_project?(quoted) do
      raise RuntimeError, "umbrella not supported in v1: #{work_copy}"
    end

    :ok
  end

  defp umbrella_project?(quoted) do
    {_quoted, found?} =
      Macro.prewalk(quoted, false, fn
        {:def, _meta, [{:project, _, args}, body]} = node, _acc when args in [[], nil] ->
          {node, keyword_has_apps_path?(body)}

        node, acc ->
          {node, acc}
      end)

    found?
  end

  defp keyword_has_apps_path?(quoted) do
    {_quoted, found?} =
      Macro.prewalk(quoted, false, fn
        list, _acc when is_list(list) ->
          {list, Keyword.keyword?(list) and Keyword.has_key?(list, :apps_path)}

        node, acc ->
          {node, acc}
      end)

    found?
  end

  defp user_mix_path(work_copy) do
    mix_user_exs = Path.join(work_copy, "mix_user.exs")

    if File.exists?(mix_user_exs) do
      mix_user_exs
    else
      Path.join(work_copy, "mix.exs")
    end
  end
end
