defmodule Mut.Bootstrap.Overlay do
  @moduledoc "Generates the working-copy mix.exs overlay."

  @type role :: :oracle | :schema | :coverage

  # Single-app wrapper module name. Kept exactly as pre-M67 so the single-app
  # overlay renders byte-for-byte identically. Umbrella apps each get a unique
  # suffix (Mutalisk.WrappedMixProject.<AppCamel>) — without that, every app's
  # mix.exs would redefine the same module in one BEAM, corrupting
  # Mix.Project.get!() and tripping Mix's app/dir-name check.
  @default_module "Mutalisk.WrappedMixProject"

  @overlay """
  # tmp/mut_work/<run_id>/mix.exs (generated by Mut.Bootstrap.Overlay)
  Code.require_file("mix_user.exs", __DIR__)
  mutalisk_user_mod = Mix.Project.get!()
  Mix.Project.pop()

  defmodule __MUTALISK_WRAPPER_MODULE__ do
    use Mix.Project

    @user_mod mutalisk_user_mod
    @mutalisk_path System.fetch_env!("MUTALISK_PATH")
    @mutalisk_role System.get_env("MUTALISK_ROLE", "schema")

    def project do
      user = @user_mod.project()

      user
      |> Keyword.update(:deps, default_deps(), &add_mutalisk_dep/1)
      |> Keyword.update(:compilers, maybe_prepend_oracle_compiler(default_compilers()), &maybe_prepend_oracle_compiler/1)
    end

    def application do
      if function_exported?(@user_mod, :application, 0) do
        @user_mod.application()
      else
        []
      end
    end

    # Used when the wrapped project declares no :deps key (e.g. the umbrella
    # root or a minimal app). Must still inject :mutalisk, otherwise its ebin
    # never reaches the code path and compile.mut_oracle is undiscoverable.
    defp default_deps, do: add_mutalisk_dep([])
    defp default_compilers, do: Mix.compilers()

    defp add_mutalisk_dep(deps) do
      if Enum.any?(deps, fn
           {:mutalisk, _} -> true
           {:mutalisk, _, _} -> true
           _ -> false
         end) do
        deps
      else
        [{:mutalisk, path: @mutalisk_path, only: [:test], runtime: true} | deps]
      end
    end

    defp maybe_prepend_oracle_compiler(compilers) do
      case @mutalisk_role do
        "oracle" -> [:mut_oracle | compilers]
        _ -> compilers
      end
    end
  end
  """

  @spec materialize(Path.t(), role) :: :ok | {:error, term}
  def materialize(work_copy, role) when role in [:oracle, :schema, :coverage] do
    mix_exs = Path.join(work_copy, "mix.exs")
    mix_user_exs = Path.join(work_copy, "mix_user.exs")

    cond do
      not File.exists?(mix_exs) ->
        {:error, {:not_a_mix_project, work_copy}}

      File.exists?(mix_user_exs) ->
        {:error, {:already_installed, work_copy}}

      Mut.Umbrella.umbrella?(work_copy) ->
        # M67: per-app overlay. The root stays an untouched `apps_path`
        # project; each child app's `mix.exs` is wrapped exactly like a
        # single-app project (rename + render), which is why the proof
        # (M66) compiled cleanly with per-app `:mutalisk` injection.
        install_umbrella_overlay(work_copy, role)

      true ->
        :ok = File.rename(mix_exs, mix_user_exs)
        File.write(mix_exs, render(role))
    end
  end

  @spec render(role) :: String.t()
  def render(role) when role in [:oracle, :schema, :coverage] do
    render(role, @default_module)
  end

  @spec render(role, String.t()) :: String.t()
  def render(role, module_name) when role in [:oracle, :schema, :coverage] do
    String.replace(@overlay, "__MUTALISK_WRAPPER_MODULE__", module_name)
  end

  # Each umbrella child app is wrapped (dep + `:mut_oracle` compiler), AND the
  # umbrella root is wrapped to inject the `:mutalisk` dep. The root injection
  # is essential, not cosmetic: Mix runs `deps.loadpaths` only once at the root
  # and then `compile.all` per child (no per-child loadpaths). Without
  # `:mutalisk` on the root's deps, its ebin never joins the code path, so
  # `compile.mut_oracle` is undiscoverable in every child. (This corrects the
  # M66 spike's "root untouched" assumption.) The root never executes the
  # prepended compiler — umbrella roots delegate compilation to children — so a
  # shared overlay is safe.
  defp install_umbrella_overlay(work_copy, role) do
    dirs = [work_copy | Mut.Umbrella.app_dirs(work_copy)]

    Enum.reduce_while(dirs, :ok, fn dir, :ok ->
      mix = Path.join(dir, "mix.exs")
      user = Path.join(dir, "mix_user.exs")

      cond do
        not File.exists?(mix) -> {:halt, {:error, {:not_a_mix_project, dir}}}
        File.exists?(user) -> {:halt, {:error, {:already_installed, dir}}}
        dir == work_copy -> wrap(mix, user, render(role))
        true -> wrap(mix, user, render(role, app_module(dir)))
      end
    end)
  end

  defp app_module(app_dir), do: @default_module <> "." <> Macro.camelize(Path.basename(app_dir))

  defp wrap(mix, user, rendered) do
    :ok = File.rename(mix, user)

    case File.write(mix, rendered) do
      :ok -> {:cont, :ok}
      {:error, _reason} = error -> {:halt, error}
    end
  end
end
